[workspace]
resolver = "2"
members = ["admin", "db", "sync", "web"]

[workspace.package]
version = "0.1.0"
authors = ["azalhu"]
edition = "2021"

[workspace.dependencies]
prost = "0.13.3"
prost-types = "0.13.3"
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread"] }
tonic = "0.12.3"
tonic-build = "0.12.3"
